development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: qusic
  pool: 5
  username: gocardless
  password:
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: qusic_test
  pool: 5
  username: gocardless
  password:
  host: 127.0.0.1